[package]
name = "world_visual"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
building_core = { path = "../../crates/building_core" }
p3_building_scenario = { path = "../../crates/p3_building_scenario" }
p4_world_scenario = { path = "../../crates/p4_world_scenario" }
scroll_camera_core = { path = "../../crates/scroll_camera_core" }
world_generation_core = { path = "../../crates/world_generation_core" }
