[package]
name = "p4_integrated_scenario"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
integrated_world_core = { path = "../integrated_world_core" }
p4_world_scenario = { path = "../p4_world_scenario" }
world_generation_core = { path = "../world_generation_core" }
